# Source: jxboot-helmfile-resources/templates/jx-gcactivities-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gcactivities
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
rules:
  - apiGroups:
      - jenkins.io
    resources:
      - pipelineactivities
    verbs:
      - list
      - delete
  - apiGroups:
      - jenkins.io
    resources:
      - environments
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - jenkins.io
    resources:
      - plugins
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - lighthouse.jenkins.io
    resources:
      - lighthousejobs
    verbs:
      - list
      - delete
