# Source: jxboot-helmfile-resources/templates/jx-basic-auth-user-password-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jx-basic-auth-user-password
  namespace: jx
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"jx-basic-auth-user-password","properties":[{"name":"username","question":"the username for basic auth ingresses","help":"The username to login to basic authenticated URLs","defaultValue":"admin"},{"name":"password","question":"the password for basic auth ingresses","help":"The password to login to basic authenticated URLs","generator":"password","minLength":5,"maxLength":41}],"mandatory":true}'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: local
  data:
    - name: password
      key: password
      property: password
    - name: username
      key: username
      property: username
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'jxboot-helmfile-resources'
        secret.jenkins-x.io/schema-object: '{"name":"jx-basic-auth-user-password","properties":[{"name":"username","question":"the username for basic auth ingresses","help":"The username to login to basic authenticated URLs","defaultValue":"admin"},{"name":"password","question":"the password for basic auth ingresses","help":"The password to login to basic authenticated URLs","generator":"password","minLength":5,"maxLength":41}],"mandatory":true}'
    type: Opaque
