# Source: jxboot-helmfile-resources/templates/owner-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: owner
  labels:
    jenkins.io/kind: "EnvironmentRole"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    title: "Team Owner"
    description: "A team owner can add/remove users and has write access to all team resources"
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  namespace: jx
rules:
  - apiGroups:
      - ""
      - jenkins.io
      - lighthouse.jenkins.io
      - extensions
      - apps
      - apiextensions.k8s.io
      - rbac.authorization.k8s.io
      - batch
      - tekton.dev
      - flagger.app
      - config.istio.io
      - authentication.istio.io
      - security.istio.io
      - networking.istio.io
      - rbac.istio.io
    resources:
      - "*"
      - "pods/*"
    verbs:
      - list
      - get
      - watch
      - create
      - update
      - patch
      - delete
