# Source: jxboot-helmfile-resources/templates/build-bot-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "tekton-bot"
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
