# Source: jxboot-helmfile-resources/templates/tekton-git-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: tekton-git
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"tekton-git","properties":[{"name":"username","question":"the pipeline username","help":"the user name used by pipelines running in Jenkins X","generator":"gitOperator.username"},{"name":"password","question":"the pipeline token or password","help":"the token or password used by pipelines running in Jenkins X","generator":"gitOperator.password"}],"mandatory":true}'
spec:
  backendType: local
  data:
    - name: password
      key: password
      property: password
    - name: username
      key: username
      property: username
  template:
    metadata:
      annotations:
        tekton.dev/git-0: "https://github.com"
        meta.helm.sh/release-name: 'jxboot-helmfile-resources'
        secret.jenkins-x.io/schema-object: '{"name":"tekton-git","properties":[{"name":"username","question":"the pipeline username","help":"the user name used by pipelines running in Jenkins X","generator":"gitOperator.username"},{"name":"password","question":"the pipeline token or password","help":"the token or password used by pipelines running in Jenkins X","generator":"gitOperator.password"}],"mandatory":true}'
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: tekton-pipelines
    type: kubernetes.io/basic-auth
