# Source: jxboot-helmfile-resources/templates/viewer-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: viewer
  labels:
    jenkins.io/kind: "EnvironmentRole"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    title: "Viewer"
    description: "A viewer can view all project resources"
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  namespace: jx
rules:
  - apiGroups:
      - ""
      - jenkins.io
      - extensions
      - apps
      - apiextensions.k8s.io
      - rbac.authorization.k8s.io
      - batch
      - tekton.dev
      - flagger.app
      - config.istio.io
      - authentication.istio.io
      - security.istio.io
      - networking.istio.io
      - rbac.istio.io
    resources:
      - "*"
    verbs:
      - list
      - get
      - watch
