# Source: jx-preview/templates/previews.preview.jenkins.io.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: previews.preview.jenkins.io
  annotations:
    meta.helm.sh/release-name: 'jx-preview'
  labels:
    gitops.jenkins-x.io/pipeline: 'customresourcedefinitions'
spec:
  group: preview.jenkins.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: URL
          type: string
          jsonPath: ".spec.pullRequest.url"
        - name: Namespace
          type: string
          jsonPath: ".spec.resources.namespace"
      schema:
        openAPIV3Schema:
          type: object
          # One can use x-kubernetes-preserve-unknown-fields: true
          # at the root of the schema (and inside any properties, additionalProperties)
          # to get the traditional CRD behaviour that nothing is pruned, despite
          # setting spec.preserveUnknownProperties: false.
          #
          # See https://kubernetes.io/blog/2019/06/20/crd-structural-schema/
          # See issue: https://github.com/knative/serving/issues/912
          x-kubernetes-preserve-unknown-fields: true
  names:
    kind: Preview
    singular: preview
    plural: previews
    shortNames:
      - pvw
  scope: Namespaced
