apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: jx/jx-install-config
  name: jx-install-config
  namespace: jx
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|jx|jx-install-config'
data:
  kubeProvider: gke
