filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
- name: twuni
  url: https://helm.twun.io
releases:
- chart: jxgh/jxboot-helmfile-resources
  version: 1.1.270
  name: jxboot-helmfile-resources
  values:
  - ../../charts/jenkins-x/jxboot-helmfile-resources/values.yaml
  - ../../versionStream/charts/jxgh/jxboot-helmfile-resources/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jenkins-x-crds
  version: 3.0.12
  name: jenkins-x-crds
  values:
  - ../../versionStream/charts/jxgh/jenkins-x-crds/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jx-pipelines-visualizer
  version: 1.8.2
  name: jx-pipelines-visualizer
  values:
  - ../../versionStream/charts/jxgh/jx-pipelines-visualizer/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jx-preview
  version: 0.0.232
  name: jx-preview
  values:
  - jx-values.yaml
- chart: jxgh/lighthouse
  version: 1.11.3
  name: lighthouse
  values:
  - ../../versionStream/charts/jxgh/lighthouse/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/bucketrepo
  version: 0.1.67
  name: bucketrepo
  values:
  - ../../versionStream/charts/jxgh/bucketrepo/values.yaml.gotmpl
  - jx-values.yaml
- chart: twuni/docker-registry
  name: docker-registry
  values:
  - ../../versionStream/charts/stable/docker-registry/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jx-build-controller
  version: 0.4.7
  name: jx-build-controller
  values:
  - ../../versionStream/charts/jxgh/jx-build-controller/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/local-external-secrets
  version: 0.0.14
  name: local-external-secrets
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
