apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata: # kpt-merge: /pullrequest
  name: pullrequest
  annotations:
    internal.kpt.dev/upstream-identifier: 'tekton.dev|PipelineRun|default|pullrequest'
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/environment/pullrequest.yaml@versionStream
          name: ""
          resources:
            # override limits for all containers here
            limits:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-env-pr.yaml@versionStream
          resources: {}
        - name: make-pr
          resources:
            # override requests for the pod here
            requests:
              cpu: 0.1
              memory: 128Mi
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
