# Source: lighthouse/templates/keeper-rb.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lighthouse-keeper
  annotations:
    meta.helm.sh/release-name: 'lighthouse'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lighthouse-keeper
subjects:
  - kind: ServiceAccount
    name: lighthouse-keeper
