# Source: lighthouse/templates/gc-jobs-role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lighthouse-gc-jobs
  annotations:
    meta.helm.sh/release-name: 'lighthouse'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - lighthouse.jenkins.io
    resources:
      - lighthousejobs
    verbs:
      - create
      - delete
      - list
      - update
      - get
      - watch
      - patch
  - apiGroups:
      - lighthouse.jenkins.io
    resources:
      - lighthousejobs/status
    verbs:
      - create
      - delete
      - list
      - update
      - get
      - watch
      - patch
